In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.decomposition import FastICA
from sklearn.random_projection import SparseRandomProjection
from sklearn.neighbors import KNeighborsClassifier
from sklearn.manifold import TSNE
import numpy as np
#import tensorflow as tf
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

## Loading Data sets

In [6]:
# Dataset 1 from Homework 1: credit cards
credit = pd.read_csv("creditcard.csv")
fraud_df = credit.loc[credit['Class'] == 1]
non_fraud_df = credit.loc[credit['Class'] == 0][:492]

normal_distributed_df = pd.concat([fraud_df, non_fraud_df])

# Shuffle dataframe rows
new_df = normal_distributed_df.sample(frac=1, random_state=42)

DATASET1 = new_df.dropna()
DATASET1 = DATASET1[['V1','V2','V3','V4','V5','V6','Class']]

X1 = DATASET1
Y1=DATASET1['Class']
X1.drop(['Class'], axis=1,inplace=True)


In [7]:
# Dataset 2 from Homework 1: Data Science Salaries
salaries = pd.read_csv("salaries.csv")
#salaries = pd.get_dummies(salaries, columns=['job_title', 'job_category', 'experience_level', 'work_setting','employment_type','company_location','company_size','salary_currency', 'salary', 'employee_residence'])
salaries['job_title'] = salaries['job_title'].str.replace('Business Intelligence','BI')
salaries['job_title'] = salaries['job_title'].str.replace('Machine Learning','ML')
salaries.drop(['salary_currency','salary'], axis = 1, inplace = True)

set1 = sorted(set(salaries['job_title']))
dictionary = {key: index for index, key in enumerate(set1)}
salaries['job_title'] = salaries['job_title'].replace(dictionary)

set1 = sorted(set(salaries["job_category"]))
dictionary = {key: index for index, key in enumerate(set1)}
salaries['job_category'] = salaries['job_category'].replace(dictionary)

set1 = sorted(set(salaries["employee_residence"]))
dictionary = {key: index for index, key in enumerate(set1)}
salaries['employee_residence'] = salaries['employee_residence'].replace(dictionary)

set1 = sorted(set(salaries["experience_level"]))
dictionary = {key: index for index, key in enumerate(set1)}
salaries['experience_level'] = salaries['experience_level'].replace(dictionary)

set1 = sorted(set(salaries["employee_residence"]))
dictionary = {key: index for index, key in enumerate(set1)}
salaries['employee_residence'] = salaries['employee_residence'].replace(dictionary)

set1 = sorted(set(salaries["employment_type"]))
dictionary = {key: index for index, key in enumerate(set1)}
salaries['employment_type'] = salaries['employment_type'].replace(dictionary)

set1 = sorted(set(salaries["work_setting"]))
dictionary = {key: index for index, key in enumerate(set1)}
salaries['work_setting'] = salaries['work_setting'].replace(dictionary)

set1 = sorted(set(salaries["company_location"]))
dictionary = {key: index for index, key in enumerate(set1)}
salaries['company_location'] = salaries['company_location'].replace(dictionary)

set1 = sorted(set(salaries["company_size"]))
dictionary = {key: index for index, key in enumerate(set1)}
salaries['company_size'] = salaries['company_size'].replace(dictionary)


DATASET2 = salaries.dropna()

DATASET2['salary_in_usd'] = DATASET2['salary_in_usd']>100000
DATASET2['salary_in_usd'] = DATASET2['salary_in_usd'].astype(int)


X2 = DATASET2
Y2=DATASET2['salary_in_usd']
X2.drop(['salary_in_usd'], axis=1,inplace=True)


### PCA

In [15]:
# Data1
pca = PCA(n_components=3)  # Reducing to 2 dimensions for visualization
X_pca = pca.fit_transform(X1)
X_pca
 

X_train1, X_test1, y_train1, y_test1 = train_test_split(X_pca, Y1, test_size=0.2, random_state=42)
knn_classifier = KNeighborsClassifier(n_neighbors=5)
knn_classifier.fit(X_train1, y_train1)

# Evaluating the classifier
accuracy = knn_classifier.score(X_test1, y_test1)
print("KNN Accuracy after PCA:", accuracy)

KNN Accuracy after PCA: 0.949238578680203


In [19]:
# Data2
pca = PCA(n_components=3)  # Reducing to 2 dimensions for visualization
X_pca = pca.fit_transform(X2)
X_pca

array([[-1.28007890e+01,  6.38976410e+01, -2.53627878e+00],
       [-1.63650227e+01, -4.66367674e+00, -1.38843191e-01],
       [-1.63650227e+01, -4.66367674e+00, -1.38843191e-01],
       ...,
       [ 5.56940533e+01, -7.27621307e+00,  9.98291083e-02],
       [ 1.17958029e+01, -5.65016387e+00,  5.39494389e-02],
       [-3.03949113e+01, -4.11916357e+00, -1.57078146e-01]])

### ICA

In [23]:
# Data1
ica = FastICA(n_components=3)  # Reducing to 2 dimensions for visualization
X_ica = ica.fit_transform(X1)
X_ica

X_train1, X_test1, y_train1, y_test1 = train_test_split(X_ica, Y1, test_size=0.2, random_state=42)
knn_classifier = KNeighborsClassifier(n_neighbors=5)
knn_classifier.fit(X_train1, y_train1)

# Evaluating the classifier
accuracy = knn_classifier.score(X_test1, y_test1)
print("KNN Accuracy after ICA:", accuracy)

KNN Accuracy after ICA: 0.9289340101522843


In [21]:
# Data2
ica = FastICA(n_components=3)  # Reducing to 2 dimensions for visualization
X_ica = ica.fit_transform(X2)
X_ica

X_train1, X_test1, y_train1, y_test1 = train_test_split(X_ica, Y2, test_size=0.2, random_state=42)
knn_classifier = KNeighborsClassifier(n_neighbors=5)
knn_classifier.fit(X_train1, y_train1)

# Evaluating the classifier
accuracy = knn_classifier.score(X_test1, y_test1)
print("KNN Accuracy after ica:", accuracy)

KNN Accuracy after ica: 0.8311063602351684


### Randomized projection

In [22]:
# Data 1
rp = SparseRandomProjection(n_components=2)  
X_rp = rp.fit_transform(X1)
X_rp

X_train1, X_test1, y_train1, y_test1 = train_test_split(X_rp, Y1, test_size=0.2, random_state=42)
knn_classifier = KNeighborsClassifier(n_neighbors=5)
knn_classifier.fit(X_train1, y_train1)

# Evaluating the classifier
accuracy = knn_classifier.score(X_test1, y_test1)
print("KNN Accuracy after rp:", accuracy)

KNN Accuracy after rp: 0.9289340101522843


In [29]:
# Data 2
rp = SparseRandomProjection(n_components=2)  
X_rp = rp.fit_transform(X2)
X_rp


array([[-2439.69178381,  2505.82800687],
       [-2448.26499791,  2560.94152608],
       [-2448.26499791,  2560.94152608],
       ...,
       [-2356.40913256,  2559.71678121],
       [-2406.62367228,  2556.04254659],
       [-2458.06295688,  2558.49203634]])

### Manifold Learning Algorithm ( t-SNE) 

In [25]:
# Data 1
tsne = TSNE(n_components=2, random_state=42)
X_tsne = tsne.fit_transform(X1)
X_tsne
X_train1, X_test1, y_train1, y_test1 = train_test_split(X_tsne, Y1, test_size=0.2, random_state=42)
knn_classifier = KNeighborsClassifier(n_neighbors=5)
knn_classifier.fit(X_train1, y_train1)

# Evaluating the classifier
accuracy = knn_classifier.score(X_test1, y_test1)
print("KNN Accuracy after tsne:", accuracy)

KNN Accuracy after tsne: 0.934010152284264


In [33]:
# Data 1
tsne = TSNE(n_components=2)
X_tsne = tsne.fit_transform(X2)
X_tsne

array([[  5.4482574, -21.90801  ],
       [ 51.563442 , -48.32477  ],
       [ 50.971054 , -47.91273  ],
       ...,
       [ 45.80226  ,  21.966759 ],
       [ 54.2793   ,  -4.8891783],
       [-14.191639 , -52.361763 ]], dtype=float32)